baseURL = "http://example.org/"
languageCode = "en-us"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
    title = "I'm Vu Hai Dang"
    author = "Vu"
    description = "Call me im6h"
    profilePicture = "https://avatars.githubusercontent.com/u/79490735?v=4"
    copyright = "2020-2021"
    fullPostContent = false
    [[params.socialIcons]]
        icon = "fab fa-linkedin"
        title = "Linkedin"
        url = "https://de.linkedin.com/"

    [[params.socialIcons]]
        icon = "fab fa-github"
        title = "GitHub"
        url = "https://github.com/im6h"
    
    [[params.socialIcons]]
        icon = "fas fa-envelope"
        title = "e-mail"
        url = "mailto:mail@example.com"

[menu]
    [[menu.main]]
        name = "Home"
        identifier = "home"
        weight = 100
        url = "/"

    [[menu.main]]
        name = "Posts"
        weight = 200
        identifier = "posts"
        url = "/post/"

    [[menu.main]]
        name = "About"
        weight = 300
        identifier = "about"
        url = "/about/"
